### ISSUE TITLE
Migrate to "-dependencies" parent pom. Solve PR's from Dependabot

### ISSUE THREAD

**Issue by abratashev** [tesler-platform/tesler#148]
We need to solve dependencies versions problems, because dependabot keeps on creating PR's with versions updates.

For example, we can use "spring-boot-starter-parent" to control most dependencies versions

I closed following PR's from dependabot:
https://github.com/tesler-platform/tesler/pull/142
https://github.com/tesler-platform/tesler/pull/139
https://github.com/tesler-platform/tesler/pull/130
https://github.com/tesler-platform/tesler/pull/110
https://github.com/tesler-platform/tesler/pull/29

**Comment by abratashev** [comment]
Also closed https://github.com/tesler-platform/tesler/pull/158

**Comment by IgorNB** [comment]
fixed all dependabot alerts in https://github.com/tesler-platform/tesler/pull/212, https://github.com/tesler-platform/tesler/pull/211, https://github.com/tesler-platform/tesler/pull/210, https://github.com/tesler-platform/tesler/pull/209, https://github.com/tesler-platform/tesler/pull/208
