### ISSUE TITLE
In backend add support of view part in url

### ISSUE THREAD

**Issue by eliantonioni** [tesler-platform/tesler#30]
We need to use current view, so have to parse view in backend when it arrives as a part of url

**Comment by abratashev** [comment]
Hi @eliantonioni 
Thanks for creating issue!

Adding context to the current view may cause cyclic dependency between layers of application. 
We specifically made the data layer independent of ui layer by adding business component abstraction.

If you describe your case, we can offer a solution that will not break the relationship between layers.

**Comment by eliantonioni** [comment]
okay, I'll close the issue
