### ISSUE TITLE
Run in Idea Spring Boot Configuration for potgresql database

### ISSUE THREAD

**Issue by ionovv** [tesler-platform/tesler#80]
When starting a project in Idea Spring Boot Configuration get an error:
Caused by: liquibase.parser.core.ParsedNodeException: Could not find directory or directory was empty for path 'db/migration/liquibase/data/latest'

**Comment by Dergash** [comment]
I believe checked `Resolve Workspace Artifacts` option may cause this, should be **unchecked** for build to work in Indea:
![resolveWorkspaceArticaftcs](https://user-images.githubusercontent.com/13132449/80413671-7c6c3080-88d8-11ea-9f03-a6f2e363f497.png)

When I've encountered this problem I found that when this option is **unchecked** the resource accesor search for resources here:
`file:/C:/Users/derga/.m2/repository/io/tesler/tesler-doc-db/1.0-SNAPSHOT/tesler-doc-db-1.0-SNAPSHOT.jar/`
and `resourceAccessor.list`  resolved in an empty list and search pattern with `*` is applied:
https://github.com/tesler-platform/tesler/blob/12d50ab9c55719b14b95a693eaaecfda61b07877/tesler-liquibase/src/main/java/liquibase/ext/tesler/ui/load/AbstractEntityChange.java#L487-L490

When this option is **checked** the recource accessor search for resources here:
`file:/C:/Users/derga/Documents/projects/tesler-doc/tesler-doc-db/target/classes/`
then this line
https://github.com/tesler-platform/tesler/blob/12d50ab9c55719b14b95a693eaaecfda61b07877/tesler-liquibase/src/main/java/liquibase/ext/tesler/ui/load/AbstractEntityChange.java#L487
resolved not in an empty list but in two strings: `db\migration\liquibase\data\latest\screens` and  `db\migration\liquibase\data\latest\widgets`, so the branch with appending `*` is not hit which results in the above error.

I was told by @abratashev that he consulted with @andreybpanfilov and the reason behind this behaviour is that `liquibase.integration.spring.SpringLiquibase.SpringResourceOpener` calculates resources differently depending on OS and the way application is launched (fat JAR or long classpath)

**Comment by IgorNB** [comment]
Tesler do not use liquibase for widgets and other meta migration since 3.0.2 version. Problem is fixed - see [example ](https://github.com/tesler-platform/tesler/wiki#:~:text=Archetype%20and%20your%20favorite%20IDE)
